sudo: required

language: generic

os:
  - linux
  - osx

env:
  global:
    - MYPYTHON_VERSION=2.7
  matrix:
    - MYUSEMC=true
    - MYUSEMC=false

matrix:
  exclude:
    - os: osx
      env: MYUSEMC=false

git:
  depth: 999999

branches:
  except:
    - /^v[0-9]/

before_install:
  - MYNAME=pyobjcryst
  - umask 022
  - git fetch origin --tags
  - if ${MYUSEMC}; then
        NOAPT=true; NOMC=false;
    else
        NOAPT=false; NOMC=true;
        MYPIPFLAGS="--user";
    fi
  - MYMCREPO=https://repo.continuum.io/miniconda
  - case ${TRAVIS_OS_NAME} in
    linux)
        MYMCBUNDLE=Miniconda2-latest-Linux-x86_64.sh ;;
    osx)
        MYMCBUNDLE=Miniconda2-latest-MacOSX-x86_64.sh ;;
    *)
        echo "Unsupported operating system." >&2;
        exit 2 ;;
    esac
  - MYRUNDIR=${PWD}/build/rundir

  - mkdir -p ~/pkgs/
  - mkdir -p ${MYRUNDIR}
  - cp .coveragerc ${MYRUNDIR}/

  - $NOMC || pushd ~/pkgs/
  - $NOMC || wget --timestamping ${MYMCREPO}/${MYMCBUNDLE}
  - $NOMC || test -x ~/mc/bin/conda || bash ${MYMCBUNDLE} -b -f -p ~/mc
  - $NOMC || popd
  - $NOMC || export PATH="${HOME}/mc/bin:${PATH}"
  - $NOMC || conda update --yes conda
  - $NOMC || conda install --yes conda-build jinja2
  - $NOMC || conda create --name=testenv --yes python=${MYPYTHON_VERSION} coverage
  - $NOMC || conda config --add channels diffpy

  - $NOAPT || test "${TRAVIS_OS_NAME}" = "linux" || exit $?
  - $NOAPT || sudo apt-get update -qq
  - $NOAPT || sudo apt-get install -y
                  python-setuptools python-numpy scons
                  build-essential python-dev libboost-all-dev
                  python-pip
  - $NOAPT || devutils/makesdist
  - $NOAPT || MYTARBUNDLE="$(ls -t "${PWD}"/dist/*.tar.gz | head -1)"
  - $NOAPT || pushd ~/pkgs
  - $NOAPT || git clone https://github.com/diffpy/libObjCryst.git
  - $NOAPT || popd

install:
  - $NOMC || conda build --python=${MYPYTHON_VERSION} --dirty conda-recipe
  - $NOMC || MYCONDATESTENV="$(ls -td ~/mc/conda-bld/${MYNAME}_*/_t_env | head -1)"
  - $NOMC || source activate ${MYCONDATESTENV:?"conda test environment not found"}
  - $NOMC || conda list  --export ${MYNAME} > /tmp/mypackage.txt
  - $NOMC || source activate testenv
  - $NOMC || conda install --yes --use-local --file=/tmp/mypackage.txt

  - $NOAPT || pip install $MYPIPFLAGS coverage
  - $NOAPT || sudo scons -C ~/pkgs/libObjCryst install
  - $NOAPT || easy_install --user "${MYTARBUNDLE}"

  - cd ${MYRUNDIR}
  - MYGIT_REV=$(python -c "import ${MYNAME}.version as v; print(v.__gitsha__)")
  - if [[ "${TRAVIS_COMMIT}" != "${MYGIT_REV}" ]]; then
        echo "Version mismatch ${TRAVIS_COMMIT} vs ${MYGIT_REV}.";
        exit 1;
    fi

script:
  - coverage run --source ${MYNAME} -m ${MYNAME}.tests.run

after_success:
  - pip install $MYPIPFLAGS codecov
  - codecov
