language: generic

os:
  - linux
  - osx

env:
  - MYUSEMC=true MYPYTHON_VERSION=2.7
  - MYUSEMC=true MYPYTHON_VERSION=3.4
  - MYUSEMC=true MYPYTHON_VERSION=3.5
  - MYUSEMC=true MYPYTHON_VERSION=3.6
  - MYUSEMC=false

git:
  depth: 999999

branches:
  except:
    - /^v[0-9]/


before_install:
  - MYNAME=pyobjcryst
  - MYCOMMIT="$(git rev-parse HEAD)"
  - umask 022
  - git fetch origin --tags
  - MYPYTHON=python; MYPIP=pip
  - NOSYS=true; NOAPT=true; NOBREW=true; NOMC=true
  - if ${MYUSEMC}; then
        NOMC=false;
    elif [[ ${TRAVIS_OS_NAME} == linux ]]; then
        NOAPT=false; NOSYS=false;
        MYPIPFLAGS="--user";
    elif [[ ${TRAVIS_OS_NAME} == osx ]]; then
        NOBREW=false; NOSYS=false;
        MYPYTHON=python3;
        MYPIP=pip3;
        MYPIPFLAGS="--user";
    fi
  - MYMCREPO=https://repo.anaconda.com/miniconda
  - case ${TRAVIS_OS_NAME} in
    linux)
        MYMCBUNDLE=Miniconda3-latest-Linux-x86_64.sh ;;
    osx)
        MYMCBUNDLE=Miniconda3-latest-MacOSX-x86_64.sh ;;
    *)
        echo "Unsupported operating system." >&2;
        exit 2 ;;
    esac
  - MYRUNDIR=${PWD}/build/rundir

  - mkdir -p ~/pkgs
  - mkdir -p ${MYRUNDIR}
  - cp .coveragerc ${MYRUNDIR}/

  - $NOMC || pushd ~/pkgs
  - $NOMC || wget --timestamping ${MYMCREPO}/${MYMCBUNDLE}
  - $NOMC || test -x ~/mc/bin/conda || bash ${MYMCBUNDLE} -b -f -p ~/mc
  - $NOMC || popd
  - $NOMC || source ~/mc/bin/activate base
  - $NOMC || conda update --yes conda
  - $NOMC || conda install --yes conda-build jinja2 scons numpy
  # Fix scons hashbang to use specific Python.
  - $NOMC || sed -i "1s,.*,#!${HOME}/mc/bin/python," ~/mc/bin/scons
  - $NOMC || conda create --name=testenv --yes python=${MYPYTHON_VERSION} coverage
  - $NOMC || conda config --add channels diffpy
  # FIXME - keep just the "diffpy" channel for public release.
  - $NOMC || conda config --add channels diffpy/channel/dev

  - $NOAPT || test "${TRAVIS_OS_NAME}" = "linux" || exit $?
  - $NOAPT || PATH="$(echo "$PATH" | sed 's,:/opt/pyenv/[^:]*,,g')"
  - $NOAPT || test "$(which python)" = "/usr/bin/python" || (
                  which python; exit 1)
  - $NOAPT || sudo apt-get update -qq
  - $NOAPT || sudo apt-get install -y
                  python-setuptools python-numpy scons
                  build-essential python-dev libboost-all-dev
                  python-pip

  - $NOBREW || test "${TRAVIS_OS_NAME}" = "osx" || exit $?
  - $NOBREW || brew update
  - $NOBREW || brew upgrade python
  - $NOBREW || brew install gcc || brew link --overwrite gcc
  - $NOBREW || brew install boost-python3
  - $NOBREW || brew install scons

  - $NOSYS || devutils/makesdist
  - $NOSYS || MYTARBUNDLE="$(ls -t "${PWD}"/dist/*.tar.gz | head -1)"
  - $NOSYS || pushd ~/pkgs
  - $NOSYS || git clone https://github.com/diffpy/libobjcryst.git
  - $NOSYS || popd


install:
  - $NOMC || conda build --python=${MYPYTHON_VERSION} conda-recipe
  - $NOMC || conda render --python=${MYPYTHON_VERSION} --output conda-recipe |
                sed 's,.*/,,; s/[.]tar[.]bz2$//; s/-/=/g' > /tmp/mypackage.txt
  - $NOMC || source activate testenv
  - $NOMC || conda install --yes --use-local --file=/tmp/mypackage.txt

  - MYSUDO=
  - $NOAPT || MYSUDO=sudo
  - $NOSYS || $MYPIP install $MYPIPFLAGS coverage
  - $NOSYS || $MYSUDO scons -C ~/pkgs/libobjcryst install
  - $NOSYS || $MYPIP install $MYPIPFLAGS "${MYTARBUNDLE}"

  - cd ${MYRUNDIR}
  - MYGIT_REV=$($MYPYTHON -c "import ${MYNAME}.version as v; print(v.__git_commit__)")
  - if [[ "${MYCOMMIT}" != "${MYGIT_REV}" ]]; then
        echo "Version mismatch ${MYCOMMIT} vs ${MYGIT_REV}.";
        exit 1;
    fi


before_script:
  - $NOBREW || USER_BASE="$(python3 -c 'import site; print(site.USER_BASE)')"
  - $NOBREW || PATH="${USER_BASE}/bin:${PATH}"


script:
  - coverage run --source ${MYNAME} -m ${MYNAME}.tests.run


after_success:
  - $MYPIP install $MYPIPFLAGS codecov
  - codecov
