{% set setupdata = load_setup_py_data() %}

package:
  name: pyobjcryst
  version: {{ setupdata['version'] }}

source:
  # git_url: https://github.com/diffpy/pyobjcryst.git
  git_url: ..

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - python
    - setuptools
    - numpy 1.11.2
    - libobjcryst >=2017.1.1,2017.1.*
    - scons
  host:
    - boost 1.67.0

  run:
    - python
    - setuptools
    - numpy >=1.11.2
    - libobjcryst >=2017.1.1,2017.1.*
    - boost 1.67.0

test:
  # Python imports
  imports:
    - pyobjcryst
    - pyobjcryst.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/diffpy/pyobjcryst
  summary: Python bindings to the ObjCryst++ crystallographic library.
  license: Modified BSD License
  license_file: LICENSE.txt

# See http://docs.continuum.io/conda/build.html
# for more information about meta.yaml.
